### ISSUE TITLE
Data from config axios need more arguments / key|value

### ISSUE THREAD

**Issue by Aromakelapa** [victorsouzaleal/fb-downloader-scrapper#1]
Hello sir, @victorsouzaleal 
i can't use this module, but i've researched your code , I've researched requests using BurpSuite and came up with { success: false }

so i try to sniff manually using brower and burpsuite, i get a request which contains some data other than 'q' :
k_token & k_exp

![image](https://user-images.githubusercontent.com/66982638/196020810-33085eaf-4f56-4f6f-a0e1-88dd4adc9a50.png)

then i try to add them to the data in the axios config and get { success: true }

but not long after, getting bad requests again.
maybe its k_exp & k_token auto-generate and expire in few minutes?

I don't understand, and that's all I know, hopefully it can solve the problem, thank you
sorry for the grammar, I use translate

**Comment by victorsouzaleal** [comment]
hey thanks for the post, i'll check it as soon as i can

**Comment by victorsouzaleal** [comment]
Yeah, I checked and they're really asking for the k_exp and the k_token in the request, I'll try to put it and make an update, ty

**Comment by victorsouzaleal** [comment]
Test the new version, if there are issues just let me know, thanks! 😸

**Comment by Aromakelapa** [comment]
wow, it works.. thankyou very much sir..
