### ISSUE TITLE
 success: false Error

### ISSUE THREAD

**Issue by geekguide** [victorsouzaleal/fb-downloader-scrapper#4]
Hi
Sir i am getting  success: false, error for every video from past 2 days
May i know How i can solve the issue

ThankYou

**Comment by Aromakelapa** [comment]
> Hi Sir i am getting success: false, error for every video from past 2 days May i know How i can solve the issue
> 
> ThankYou

bcz response from fdownloader.net return a encrypted result. you can check in DevTools on tab network after you click download
